export const mockData = [
    {
        id: 29,
        atc1_code: "B0 BLOOD + B.FORMING ORGANS",
        atc3: "B05X",
        cargo_destination: "COMMERCIAL",
        dosage: "0.9% 10ML",
        dosage_old: "0.9% 10ML",
        dosage_old2: "0.9% 10ML",
        drug_form: "AMPOULE",
        drug_form_old: "AMPOULE",
        inn_new: "SODIUM CHLORIDE",
        inn_old: "SODIUM CHLORIDE",
        interested_party_stand: "GROTEX",
        manufacturing_company: "«GROTEX» LTD",
        manufacturing_company_stand: "GROTEX",
        mode_of_registration: "NATIONAL",
        number_of_molecules: 0,
        pack_quantity: 10,
        person_interested_in_registration_georgia_stand: "GROTEX",
        person_with_trading_license_stand: "GROTEX",
        price_per_unit: 6.5,
        price_per_unit_usd: 2.34,
        registration_date: "2024-03-12",
        rx_otc: "OTC",
        sku_from_database: "SODIUM CHLORIDE 0.9% 10ML SOLUTION FOR INJECTION LDPE AMPOULES NO. 10",
        sku_old: "SODIUM CHLORIDE 0.9% 10ML SOLUTION FOR INJECTION LDPE AMPOULES NO. 10",
        sku_our_db: "SODIUM CHLORIDE 0.9% 10ML AMPOULE NO.10",
        trade_name: "SODIUM CHLORIDE",
        value: 135707.0,
        value_in_usd: 48854.52,
        volume: 20878.0,
        year: 2024,
    },
    {
        id: 30,
        atc1_code: "B0 BLOOD + B.FORMING ORGANS",
        atc3: "B05X",
        cargo_destination: "COMMERCIAL",
        dosage: "0.9% 5ML",
        dosage_old: "0.9% 5ML",
        dosage_old2: "0.9% 5ML",
        drug_form: "AMPOULE",
        drug_form_old: "AMPOULE",
        inn_new: "SODIUM CHLORIDE",
        inn_old: "SODIUM CHLORIDE",
        interested_party_stand: "TIMEFARM",
        manufacturing_company: "«GROTEX» LTD",
        manufacturing_company_stand: "GROTEX",
        mode_of_registration: "NATIONAL",
        number_of_molecules: 0,
        pack_quantity: 10,
        person_interested_in_registration_georgia_stand: "GROTEX",
        person_with_trading_license_stand: "GROTEX",
        price_per_unit: 2.95,
        price_per_unit_usd: 1.06,
        registration_date: "2024-04-11",
        rx_otc: "OTC",
        sku_from_database: "SODIUM CHLORIDE  0.9% 5ML SOLUTION FOR INJECTION LDPE AMPOULES NO. 10",
        sku_old: "SODIUM CHLORIDE  0.9% 5ML SOLUTION FOR INJECTION LDPE AMPOULES NO. 10",
        sku_our_db: "SODIUM CHLORIDE 0.9% 5ML AMPOULE NO.10",
        trade_name: "SODIUM CHLORIDE",
        value: 73384.2,
        value_in_usd: 26418.31,
        volume: 24876.0,
        year: 2024,
    },
    {
        id: 31,
        atc1_code: "B0 BLOOD + B.FORMING ORGANS",
        atc3: "B05X",
        cargo_destination: "COMMERCIAL",
        dosage: "0.9% 5ML",
        dosage_old: "0.9% 5ML",
        dosage_old2: "0.9% 5ML",
        drug_form: "AMPOULE",
        drug_form_old: "AMPOULE",
        inn_new: "SODIUM CHLORIDE",
        inn_old: "SODIUM CHLORIDE",
        interested_party_stand: "TIMEFARM",
        manufacturing_company: "«GROTEX» LTD",
        manufacturing_company_stand: "GROTEX",
        mode_of_registration: "NATIONAL",
        number_of_molecules: 0,
        pack_quantity: 10,
        person_interested_in_registration_georgia_stand: "GROTEX",
        person_with_trading_license_stand: "GROTEX",
        price_per_unit: 2.95,
        price_per_unit_usd: 1.06,
        registration_date: "2024-02-18",
        rx_otc: "OTC",
        sku_from_database: "SODIUM CHLORIDE  0.9% 5ML SOLUTION FOR INJECTION LDPE AMPOULES NO. 10",
        sku_old: "SODIUM CHLORIDE  0.9% 5ML SOLUTION FOR INJECTION LDPE AMPOULES NO. 10",
        sku_our_db: "SODIUM CHLORIDE 0.9% 5ML AMPOULE NO.10",
        trade_name: "SODIUM CHLORIDE",
        value: 58188.75,
        value_in_usd: 20947.95,
        volume: 19725.0,
        year: 2024,
    },
    {
        id: 25,
        atc1_code: "V0 VARIOUS",
        atc3: "V03A",
        cargo_destination: "COMMERCIAL",
        dosage: "10MG/ML 5ML",
        dosage_old: "10MG/ML 5ML",
        dosage_old2: "10MG/ML 5ML",
        drug_form: "AMPOULE",
        drug_form_old: "AMPOULE",
        inn_new: "PROTAMINE SULFATE",
        inn_old: "PROTAMINE SULFATE",
        interested_party_stand: "MLC MEDICAL",
        manufacturing_company: "HANLIM PHARM. CO., LTD.",
        manufacturing_company_stand: "HANLIM PHARM",
        mode_of_registration: "CONFESSIONAL",
        number_of_molecules: 0,
        pack_quantity: 5,
        person_interested_in_registration_georgia_stand: "N/A",
        person_with_trading_license_stand: "HANLIM PHARM",
        price_per_unit: 64.3,
        price_per_unit_usd: 23.15,
        registration_date: "2024-07-03",
        rx_otc: "RX",
        sku_from_database: "",
        sku_old: "",
        sku_our_db: "",
        trade_name: "PROTAMINE SULFATE",
        value: 0,
        value_in_usd: 0,
        volume: 0,
        year: 2024,
    },
];

export const allATC1 = [{name: "asdf", id: 4}]
